### ISSUE TITLE
Feature Request - Support for Next Gen Dynamic Media URL Handling

### ISSUE THREAD

**Issue by nhirrle** [wcm-io/io.wcm.handler.media#43]
With one of the latest updates to AEM Core Components, support Adobe's Next Gen Dynamic Media / Project Polaris was added:
https://github.com/adobe/aem-core-wcm-components/releases/tag/core.wcm.components.reactor-2.23.0

More info on it: https://experienceleaguecommunities.adobe.com/t5/adobe-experience-manager/adobe-developers-live-may-2023-seamless-integration-of/td-p/591130

It would be great to enhance MediaHandler API to support as well what was created in https://github.com/adobe/aem-core-wcm-components/blob/main/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v3/NextGenDMImageURIBuilder.java but with a public interface or just add it as part of the current classes with a flag for nextGenDMImage.

**Comment by stefanseifert** [comment]
an experimental support is already built into media handler 2.0.0 (released on friday), PR #38
it will be improved in subsequent releases (e.g. it is planned to support also non-image assets, and to optionally check for existance/metadata of the references asset)

**Comment by nhirrle** [comment]
in this case we can just close the ticket. looking forward to the release!
