### ISSUE TITLE
Add support for multiple in-place editors

### ISSUE THREAD

**Issue by brunonetcentric** [wcm-io/io.wcm.handler.media#70]
### Description
I encountered a limitation when implementing the wcm.io Responsive Image (v1) component with multiple in-place editors (inline editing options for image and text), as documented by Adobe: [Adobe Docs: Multiple In-Place Editors](https://experienceleague.adobe.com/en/docs/experience-manager-65/content/implementing/developing/components/multiple-inplace-editors).

### Problem
Currently, the _DamMediaSource_ class restricts allowed in-place editor (IPE) types (see [DamMediaSource.java](https://github.com/wcm-io/io.wcm.handler.media/blob/develop/src/main/java/io/wcm/handler/mediasource/dam/DamMediaSource.java#L231)). This leads to _MediaHandlerConfig_, which, in turn, defaults to _MediaMarkupBuilderUtil.DEFAULT_ALLOWED_IPE_EDITOR_TYPES_ — permitting only the "image" editor type (see [line 290 in MediaHandlerConfig](https://github.com/wcm-io/io.wcm.handler.media/blob/develop/src/main/java/io/wcm/handler/media/spi/MediaHandlerConfig.java#L290) and [line 62 in MediaMarkupBuilderUtil](https://github.com/wcm-io/io.wcm.handler.media/blob/develop/src/main/java/io/wcm/handler/media/markup/MediaMarkupBuilderUtil.java#L62)).

To utilize both inline text and image options concurrently, support for the "hybrid" editor type is required. Currently, this isn’t possible due to the restrictive configuration within the DEFAULT_ALLOWED_IPE_EDITOR_TYPES, which only allows _Set.of("image")_.

### Proposal
To support scenarios that require multiple in-place editor types, this change would align with Adobe's multiple in-place editor functionality.

Thank you for considering this feature request. Let me know if more information or clarification is needed!

**Comment by brunonetcentric** [comment]
Thank you for replying, I will try this solution and create a PR if it works as expected, when I have some time :)

**Comment by stefanseifert** [comment]
i just remembered we already implemented a solution for this - the list of allowed IP editor types is already configurable. have a look at PR #14.
please reopen the ticket if it does not solve your problem.

**Comment by brunonetcentric** [comment]
Thank you @stefanseifert, works like a charm!
